### ISSUE TITLE
The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -2139076795

### ISSUE THREAD

**Issue by Mupli** [e3dio/packBytes#12]
Getting error .. 

The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -2139076795

  const pb = new PackBytes(string);
  pb.encode(html)

wanted to encode whole html page as a test..

**Comment by e3dio** [comment]
works fine:

```js
import { string, PackBytes } from 'packbytes';

const schema = string;

const encoder = new PackBytes(schema);

const buf = encoder.encode('123');
console.log('buf:', buf); // Uint8Array(4) [ 3, 49, 50, 51 ]

const str = encoder.decode(buf);
console.log('string:', str); // 123
```

**Comment by e3dio** [comment]
I do see issue with large strings over certain size, master branch has work in progress for this issue https://github.com/e3dio/packBytes/issues/9 which currently throws an error for large string, I will fix that

**Comment by e3dio** [comment]
But you should be seeing a different error, this: `RangeError: Invalid typed array length`

**Comment by e3dio** [comment]
Ok I finish open issue https://github.com/e3dio/packBytes/issues/9 and it should work for you now, retry

**Comment by Mupli** [comment]
@e3dio 
Hi, now I have different problem .. (the same code)

```
.../node_modules/packbytes/packbytes.mjs:276
                        this.dataview = new DataView(this.dataview.buffer.transfer(this.dataview.byteLength * 2));
                                                                          ^
TypeError: this.dataview.buffer.transfer is not a function
    at PackBytes.checkSize ( .../node_modules/packbytes/packbytes.mjs:276:54)
    at PackBytes.writeString (.../node_modules/packbytes/packbytes.mjs:216:8)
    at Object.encode (.../node_modules/packbytes/packbytes.mjs:46:113)
    at PackBytes.encode (.../node_modules/packbytes/packbytes.mjs:10:26)

**Comment by Mupli** [comment]
Buffer.byteLength(html)
18245

**Comment by e3dio** [comment]
Ah `ArrayBuffer.transfer()` might only be available in Node v22, you must be on older Node. I guess I need to change that to be backwards compatible

**Comment by Mupli** [comment]
yeah I'm still on 18 LTS. I need to upgrade....

**Comment by e3dio** [comment]
Wow that is really old, can you at least try Node v20 or v22

**Comment by e3dio** [comment]
I will make it backwards compatible

**Comment by Mupli** [comment]
yeah v20 ..same issue. I think this transfer is a recent improvement

**Comment by e3dio** [comment]
It's a V8 feature available starting in Node v21 https://github.com/nodejs/node/pull/49639

 I pushed update, should work now

**Comment by Mupli** [comment]
I think it works. could you publish new version

**Comment by Mupli** [comment]
btw. do you have discord ?
