### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by yovanoc** [e3dio/packBytes#6]
Could be a great idea to have it rewrite in TS to have something like this project https://github.com/voltrevo/monorepo/tree/master/projects/typed-bytes

packBytes is really great but we can't know the TS type for the final object shape

**Comment by e3dio** [comment]
I don't use typescript out of personal preference and have no real experience using it so I can't comment much on it, it seems like you should be able to use packBytes with a Typescript project but it will just not auto-generate types for you? You say "we can't know the TS type for the final object shape" but you create the schema so you should know the types, you should be able to create your own type for that data very easily, and don't need the library to create it for you from what I understand, is that correct?

**Comment by yovanoc** [comment]
Yeah u right the developer knows but not TS as in this example

<img width="468" alt="image" src="https://user-images.githubusercontent.com/7302317/189486367-02f5ba1a-842a-4d88-b49e-289d23b04197.png">

but yeah I imagine I have to fork your repo and do it myself then :/

**Comment by e3dio** [comment]
Go for it dude, seems very easy to create a type for your own data, no need to over-complicate the library to do something that takes you literally 2 seconds to do on your own

**Comment by e3dio** [comment]
Seems like all you need to do is create a function that recursively scans the Schema similar to the [scanSchema](https://github.com/e3dio/packBytes/blob/main/packbytes.mjs#L32) function and have it return the types for each field, should not be hard. This is not something I have the knowledge to do but you are welcome to create your own wrapper library to add that in. It might be useful for people who use Typescript

**Comment by yovanoc** [comment]
Yeah I think I will look at it in the next weeks, will tell you
